Server/Sesame.Web/ViewModels/Authorization/AuthorizeViewModel.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace WebApplication1.ViewModels.Authorization
{
    public class AuthorizeViewModel
    {
        [Display(Name = "Application")]
        public string ApplicationName { get; set; }

        [BindNever]
        public string RequestId { get; set; }

        [Display(Name = "Scope")]
        public string Scope { get; set; }

        public string RedirectUri { get; set; }
    }
}

Server/Sesame.Web/ViewModels/Authorization/LogoutViewModel.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace Sesame.Web.ViewModels.Authorization
{
    public class LogoutViewModel
    {
        [BindNever]
        public string RequestId { get; set; }
    }
}

Server/Sesame.Web/Controllers/AuthorizationController.cs
/*
 * Licensed under the Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
 * See https://github.com/openiddict/openiddict-core for more information concerning
 * the license and the contributors participating to this project.
 */

using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using AspNet.Security.OpenIdConnect.Extensions;
using AspNet.Security.OpenIdConnect.Primitives;
using AspNet.Security.OpenIdConnect.Server;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using OpenIddict.Core;
using OpenIddict.Models;
using Sesame.Web.Contracts;
using Sesame.Web.Helpers;
using Sesame.Web.Services;
using Sesame.Web.ViewModels.Authorization;
using Sesame.Web.ViewModels.Shared;
using Universal.Microsoft.CognitiveServices.SpeakerRecognition;
using WebApplication1.ViewModels.Authorization;


namespace Sesame.Web.Controllers
{
    /// <summary>
    /// Main controller that handles the OAuth flow
    /// </summary>
    public class AuthorizationController : Controller
    {
        private readonly OpenIddictApplicationManager<OpenIddictApplication> _applicationManager;
        private readonly IOptions<IdentityOptions> _identityOptions;
        private readonly ISessionStateService _sessionStateService;

        public AuthorizationController(
            OpenIddictApplicationManager<OpenIddictApplication> applicationManager,
            IOptions<IdentityOptions> identityOptions,
            ISessionStateService sessionStateService,
            IPersistentStorageService persistantStorageService, 
            SpeakerRecognitionClient speakerRecognitionClient)
        {
            _applicationManager = applicationManager;
            _identityOptions = identityOptions;
            _sessionStateService = sessionStateService;
        }

        /// <summary>
        /// This action handles the initial request and will show the login page. 
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpGet("~/connect/authorize")]
        public async Task<IActionResult> Authorize(OpenIdConnectRequest request)
        {
            Debug.Assert(request.IsAuthorizationRequest(),
                "The OpenIddict binder for ASP.NET Core MVC is not registered. " +
                "Make sure services.AddOpenIddict().AddMvcBinders() is correctly called.");

            // Retrieve the application details from the OpenIddict database.
            var application = await _applicationManager.FindByClientIdAsync(request.ClientId, HttpContext.RequestAborted);
            if (application == null)
            {
                return View("Error", new ErrorViewModel
                {
                    Error = OpenIdConnectConstants.Errors.InvalidClient,
                    ErrorDescription = "Details concerning the calling client application cannot be found in the database"
                });
            }

            // Flow the request_id to allow OpenIddict to restore
            // the original authorization request from the cache.
            return View(new AuthorizeViewModel
            {
                ApplicationName = application.DisplayName,
                RequestId = request.RequestId,
                Scope = request.Scope,
                RedirectUri=request.RedirectUri
            });
        }

        /// <summary>
        /// When the user side code indicates it is ready to accept the authentication request
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
       
        [HttpPost("~/connect/authorize"), ValidateAntiForgeryToken]
        public async Task<IActionResult> Accept(OpenIdConnectRequest request)
        {
            if (!_sessionStateService.Get<bool>("VoiceAuthenticated"))
            {
               return Forbid(OpenIdConnectServerDefaults.AuthenticationScheme);
            }

            var userNameId = _sessionStateService.Get<string>("UserPrincipalName");

            if (userNameId == null)
            {
                return Forbid(OpenIdConnectServerDefaults.AuthenticationScheme);
            }

            var identity = new ClaimsIdentity(
                OpenIdConnectServerDefaults.AuthenticationScheme,
                OpenIdConnectConstants.Claims.Name,
                OpenIdConnectConstants.Claims.Role);

            // Add a "sub" claim containing the user identifier, and attach
            // the "access_token" destination to allow OpenIddict to store it
            //// in the access token, so it can be retrieved from your controllers.
            identity.AddClaim(OpenIdConnectConstants.Claims.Subject, userNameId,
                OpenIdConnectConstants.Destinations.AccessToken);
            identity.AddClaim(OpenIdConnectConstants.Claims.Name, userNameId,
                OpenIdConnectConstants.Destinations.AccessToken);

            identity.AddClaim("YourOwnClaim", "Your own claim value",
                OpenIdConnectConstants.Destinations.AccessToken);

            //Add a claim to the ID token
            identity.AddClaim("SomeIDTokenClaim", "SomeIDTokenClaimValue",
                OpenIdConnectConstants.Destinations.IdentityToken);
            // ... add other claims, if necessary.

            var principal = new ClaimsPrincipal(identity);
            // Ask OpenIddict to generate a new token and return an OAuth2 token response.
            return SignIn(principal, OpenIdConnectServerDefaults.AuthenticationScheme);
        }

        /// <summary>
        /// The client side code has rejected the request
        /// </summary>
        /// <returns></returns>
        [FormValueRequired("submit.Deny")]
        [HttpPost("~/connect/authorize"), ValidateAntiForgeryToken]
        public IActionResult Deny()
        {
            // Notify OpenIddict that the authorization grant has been denied by the resource owner
            // to redirect the user agent to the client application using the appropriate response_mode.
            return Forbid(OpenIdConnectServerDefaults.AuthenticationScheme);
        }

        [HttpGet("~/connect/logout")]
        public IActionResult Logout(OpenIdConnectRequest request)
        {
            // Flow the request_id to allow OpenIddict to restore
            // the original logout request from the distributed cache.
            return View(new LogoutViewModel
            {
                RequestId = request.RequestId,
            });
        }

        [HttpPost("~/connect/logout"), ValidateAntiForgeryToken]
        public async Task<IActionResult> Logout()
        {
            // Ask ASP.NET Core Identity to delete the local and external cookies created
            // when the user agent is redirected from the external identity provider
            // after a successful authentication flow (e.g Google or Facebook).
           // await _signInManager.SignOutAsync();

            // Returning a SignOutResult will ask OpenIddict to redirect the user agent
            // to the post_logout_redirect_uri specified by the client application.
            return SignOut(OpenIdConnectServerDefaults.AuthenticationScheme);
        }

        /// <summary>
        /// Generate an access token to send back for the client. This is the last step of the flow in this app. 
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost("~/connect/token"), Produces("application/json")]
        public async Task<IActionResult> Exchange(OpenIdConnectRequest request)
        {
            Debug.Assert(request.IsTokenRequest(),
                "The OpenIddict binder for ASP.NET Core MVC is not registered. " +
                "Make sure services.AddOpenIddict().AddMvcBinders() is correctly called.");

            if (request.IsAuthorizationCodeGrantType())
            {
                // Retrieve the claims principal stored in the authorization code.
                var info = await HttpContext.AuthenticateAsync(OpenIdConnectServerDefaults.AuthenticationScheme);


                //You may be interested in this sample code from OpenIddict samples on how to do this with ASP.NET Core Authentication. 
                //In this case however we just pass through the token information that was generated in the Accept action. 


                // Retrieve the user profile corresponding to the authorization code.
                // Note: if you want to automatically invalidate the authorization code
                // when the user password/roles change, use the following line instead:
                // var user = _signInManager.ValidateSecurityStampAsync(info.Principal);
                //var user = await _userManager.GetUserAsync(info.Principal);
                //if (user == null)
                //{
                //    return BadRequest(new OpenIdConnectResponse
                //    {
                //        Error = OpenIdConnectConstants.Errors.InvalidGrant,
                //        ErrorDescription = "The authorization code is no longer valid."
                //    });
                //}

                // Ensure the user is still allowed to sign in.
                //if (!await _signInManager.CanSignInAsync(user))
                //{
                //    return BadRequest(new OpenIdConnectResponse
                //    {
                //        Error = OpenIdConnectConstants.Errors.InvalidGrant,
                //        ErrorDescription = "The user is no longer allowed to sign in."
                //    });
                //}

                // Create a new authentication ticket, but reuse the properties stored
                // in the authorization code, including the scopes originally granted.
                var ticket = await CreateTicketAsync(request, info);

Server/Sesame.Web/Views/Authorization/Authorize.cshtml
@model WebApplication1.ViewModels.Authorization.AuthorizeViewModel
@{
    ViewData["Title"] = "About";
}


<main role="main">


    <div class="jumbotron">
        <h1>Authorization</h1>

        @*<p class="lead text-left">Do you want to grant <strong>@Model.ApplicationName</strong> access to your data? (scopes requested: @Model.Scope)</p>
        *@
        <form method="post" id="authenticationform">
            @Html.AntiForgeryToken()

            <input type="hidden" name="redirect_uri" value="@Model.RedirectUri" />
            <input type="hidden" name="request_id" value="@Model.RequestId" />

            <input class="btn btn-lg btn-success hidden" name="submit.Accept" type="submit" value="Yes" />
            @*<input class="btn btn-lg btn-danger hidden" name="submit.Deny" type="submit" value="No" />*@
        </form>
    </div>


    <div id="welcome-screen">
        <div class="row" align="center">
            <div class="col-sm-12">
                <p> Welcome</p>
                <p>Press space to begin</p>
            </div>
        </div>
    </div>


    <div id="profile-screen">
        <div class="row" align="center">
            <div class="col-sm-12">

                <form class="login-group">
                    <label for="pin" id="pinload">Loading</label>
                    <label for="pin">What's your pin?</label>
                    <input type="number" name="pin" id="pin" autofocus />

                    <button type="submit" id="pinsubmit" class="btn btn-default">Submit</button>
                </form>
            </div>
        </div>
    </div>


    <div id="verify-screen">
        <div class="row" align="center">
            <div class="col-sm-12">

                <p id="verify-prompt"></p>
            </div>
        </div>
        <div class="row" align="center">
            <div class="col-sm-12">
                <div id="viz">
                    <canvas id="analyser" height="50"></canvas>
                    <canvas id="wavedisplay" height="50"></canvas>
                </div>
            </div>
        </div>
        <div class="row  " align="center">
            <div class="col-sm-12">
                <p id="verificationphrase"> </p>
                <p id="message"></p>
            </div>
        </div>

        <div class="row" align="center">
            <div class="col-sm-12">
                <div id="controls">
                    <img id="record" src="/images/mic128.png" onclick="toggleRecording(this);">
                    <a id="save" href="#">
                        <img src="/images/save.svg">
                    </a>
                </div>

            </div>



        </div>
    </div>


</main>

@section scripts{
    <script src="~/js/audiodisplay.js"></script>
    <script src="~/js/recorderjs/recorder.js"></script>
    <script src="~/js/login.js"></script>
    <script src="~/js/main.js"></script>
}

Server/Sesame.Web/Views/Authorization/Logout.cshtml
@model Sesame.Web.ViewModels.Authorization.LogoutViewModel

<div class="jumbotron">
    <h1>Log out</h1>
    <p class="lead text-left">Are you sure you want to sign out?</p>

    <form asp-controller="Authorization" asp-action="Logout" method="post">
        <input type="hidden" name="request_id" value="@Model.RequestId" />

        <input class="btn btn-lg btn-success" name="Confirm" type="submit" value="Yes" />
    </form>
</div>